<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTransactionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('transactions', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->unsigned();
            $table->integer('doctor_id')->unsigned();
            $table->integer('appointment_id')->unsigned();

            // Money Related
            $table->integer('amount')->default(0);        // Amount Paid
            $table->string('currency')->default('usd');   // USD, BTC

            // Transaction Related
            $table->tinyInteger('channel')->nullable();   // Payment Channel [Bank Deposit, Mobile/Online, Online Payment Processor]
            $table->string('transaction_id'); // Trxn ID generated in-app.
            $table->integer('processor_id')->unsigned()->nullable(); // Payment processor used
            $table->string('processor_trxn_id')->nullable(); // Trxn ID generated by processor or bank deposit number
            $table->tinyInteger('status')->default(2);    // 1:Successful, 2:Ongoing, 3:Unsuccessful

            // Time Related 
            $table->timestamp('confirmed_at')->nullable();// Datetime transaction completed successfully.
            $table->timestamp('cancelled_at')->nullable();// Datetime transcation failed/cancelled.
            $table->timestamps();

            $table->foreign('user_id')
                  ->references('id')->on('users')
                  ->onDelete('cascade')->onUpdate('cascade');
            $table->foreign('doctor_id')
                  ->references('id')->on('doctors')
                  ->onDelete('cascade')->onUpdate('cascade');
            $table->foreign('appointment_id')
                  ->references('id')->on('appointments')
                  ->onDelete('cascade')->onUpdate('cascade');
            // $table->foreign('processor_id')
            //       ->references('id')->on('processors')
            //       ->onDelete('cascade')->onUpdate('cascade');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('transactions');
    }
}
